In [1]:
import os

os.getcwd()

'/media/hamza/Disque local/Hamza Bouajila/Portfolio/Building-a-Batch-ETL-Pipeline-RedPanda/notebooks'

In [2]:
os.chdir("../")
os.getcwd()

'/media/hamza/Disque local/Hamza Bouajila/Portfolio/Building-a-Batch-ETL-Pipeline-RedPanda'

In [3]:
from data_pipeline.src.core.config import settings
import duckdb

# Initiate a MotherDuck connection using an access token
con = duckdb.connect(f"md:StreamingApp?motherduck_token={settings.MOTHERDUCK_TOKEN}")

In [4]:
con

In [5]:
con.sql("SHOW DATABASES").show()

┌───────────────────────┐
│     database_name     │
│        varchar        │
├───────────────────────┤
│ StreamingApp          │
│ md_information_schema │
│ my_db                 │
│ sample_data           │
└───────────────────────┘

In [6]:
con.sql("SELECT current_database()").fetchdf()

  current_database()
0       StreamingApp

In [5]:
con.sql("USE main")

In [8]:
con.sql("SELECT current_database()").fetchdf()

  current_database()
0       StreamingApp

In [6]:
con.sql("SHOW TABLES")

┌─────────────┐
│    name     │
│   varchar   │
├─────────────┤
│ BitcoinData │
│ NewsData    │
└─────────────┘

In [17]:
# Check if table exists
table_name = "Coin"
table_exists = (
    con.sql(
        f"SELECT COUNT(*) FROM information_schema.tables WHERE table_name = '{table_name}'"
    ).fetchone()[0]
    > 0
)

if not table_exists:
    # Create table if it does not exist
    con.sql(f"CREATE TABLE {table_name} (column1 VARCHAR, column2 VARCHAR)")

# Insert data into the table
con.sql(f"INSERT INTO {table_name} VALUES ('value1', 'value2')")

In [11]:
con.sql("""
            CREATE TABLE IF NOT EXISTS BitcoinData (
                price VARCHAR(255),
                volume_24h VARCHAR(255),
                volume_change_24h VARCHAR(255),
                percent_change_1h VARCHAR(255),
                percent_change_24h VARCHAR(255),
                percent_change_7d VARCHAR(255),
                market_cap VARCHAR(255),
                market_cap_dominance VARCHAR(255),
                fully_diluted_market_cap VARCHAR(255),
                last_updated VARCHAR(255)
            );
        """)

In [14]:
doc = {
    "title": "Can Bangladesh and India transcend South Asia colonial legacies?",
    "description": "broader question whether south asia transcend legacy colonialism embrace model cooperation prioritises collective wellbeing individual dominance",
    "pubDate": "2025-01-03 06:00:00",
    "source": "The Daily Star",
}

In [15]:
con.sql(
    f"""INSERT INTO NewsData (description, source, pubDate, title)
    VALUES (
    '{doc["description"]}',
    '{doc["source"]}',
    '{doc["pubDate"]}',
    '{doc["title"]}'
)
    """
)

In [11]:
con.sql("SELECT * FROM NewsData").df()

,description,source,pubDate,title
0,বলদশ জমযত ইসলমর আমর ড শফকর রহমন বলছন আমর বদশ ব...,দৈনিক ইত্তেফাক | The Daily Ittefaq,2025-01-03 08:15:16,"বিদেশে বন্ধু চাই, প্রভু নয়: জামায়াত আমির"
1,one major problem current healthcare system la...,The Daily Star,2025-01-03 07:00:00,Pharmacies can become urban primary healthcare...
2,বলদশ জমযত ইসলমর আমর ড শফকর রহমন বলছন আমর বদশ ব...,দৈনিক ইত্তেফাক | The Daily Ittefaq,2025-01-03 08:15:16,"বিদেশে বন্ধু চাই, প্রভু নয়: জামায়াত আমির"
3,one major problem current healthcare system la...,The Daily Star,2025-01-03 07:00:00,Pharmacies can become urban primary healthcare...
4,বলদশ জমযত ইসলমর আমর ড শফকর রহমন বলছন আমর বদশ ব...,দৈনিক ইত্তেফাক | The Daily Ittefaq,2025-01-03 08:15:16,"বিদেশে বন্ধু চাই, প্রভু নয়: জামায়াত আমির"
...,...,...,...,...
137,also santa cruz wharf collapse bird activist c...,East Bay Times,2025-01-04 00:30:15,letter jimmy carter sought peace palestinian
138,el presidente se reunira con la familias en du...,El Diario Ny,2025-01-04 00:30:00,joe biden visitara nueva orleans tras ataque q...
139,speaker mike johnson continue lead house repub...,Unionleader,2025-01-04 00:30:00,mike johnson clinched speakership assist trump
140,caltrans planning multiple overnight closure f...,Abc7,2025-01-04 00:28:04,freeway overnight closure planned next week co...
141,speaker mike johnson narrowly avoided painful ...,The New York Times,2025-01-04 00:26:54,johnson reward speaker impossible job deliveri...